if (self.CavalryLogger) { CavalryLogger.start_js(["mjPPy"]); }

__d("XCometLWIProductPickerControllerRouteBuilder",["cometRouteBuilder"],(function(a,b,c,d,e,f){a=b("cometRouteBuilder")("/ad_center/create/ad/",Object.freeze({}),void 0);e.exports=a}),null);
__d("XCometLWIPurchaseCreationControllerRouteBuilder",["cometRouteBuilder"],(function(a,b,c,d,e,f){a=b("cometRouteBuilder")("/ad_center/create/purchasead/",Object.freeze({}),void 0);e.exports=a}),null);
__d("XCometPageVanityControllerRouteBuilder",["cometRouteBuilder"],(function(a,b,c,d,e,f){a=b("cometRouteBuilder")("/{vanity}/",Object.freeze({}),void 0);e.exports=a}),null);
__d("CometFeedPageVerifiedBadgeStrategy_badge$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a={kind:"ScalarField",alias:null,name:"__typename",args:null,storageKey:null},b={kind:"ScalarField",alias:null,name:"id",args:null,storageKey:null};return{kind:"SplitOperation",name:"CometFeedPageVerifiedBadgeStrategy_badge$normalization",metadata:{derivedFrom:"CometFeedPageVerifiedBadgeStrategy_badge"},selections:[a,{kind:"ScalarField",alias:null,name:"is_prod_eligible",args:null,storageKey:null},{kind:"LinkedField",alias:null,name:"story",storageKey:null,args:null,concreteType:"Story",plural:!1,selections:[{kind:"LinkedField",alias:null,name:"actors",storageKey:null,args:null,concreteType:null,plural:!0,selections:[a,{kind:"InlineFragment",type:"Page",selections:[{kind:"ScalarField",alias:null,name:"verification_status",args:null,storageKey:null}]},b]},b]}]}}();e.exports=a}),null);
__d("CometFeedPageVerifiedBadgeStrategy_badge.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"Fragment",name:"CometFeedPageVerifiedBadgeStrategy_badge",type:"CometFeedPageVerifiedBadgeStrategy",metadata:null,argumentDefinitions:[],selections:[{kind:"LinkedField",alias:null,name:"story",storageKey:null,args:null,concreteType:"Story",plural:!1,selections:[{kind:"LinkedField",alias:null,name:"actors",storageKey:null,args:null,concreteType:null,plural:!0,selections:[{kind:"FragmentSpread",name:"CometPageVerificationBadge_page",args:null}]}]},{kind:"FragmentSpread",name:"useCometFeedStoryMatchDebugger_iCometStorySection",args:null}]};e.exports=a}),null);
__d("CometPageVerificationBadge_page.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"Fragment",name:"CometPageVerificationBadge_page",type:"Page",metadata:null,argumentDefinitions:[],selections:[{kind:"ScalarField",alias:null,name:"verification_status",args:null,storageKey:null}]};e.exports=a}),null);
__d("CometPageVerificationBadge.react",["CometLazyPopoverTrigger.react","CometPageVerificationIcon.react","CometRelay","JSResource","React","CometPageVerificationBadge_page.graphql"],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g;b("CometRelay").graphql;var h=b("CometRelay").useFragment,i=b("JSResource")("CometVerificationBadgeInfoPopover.react").__setRef("CometPageVerificationBadge.react");function a(a){var c=a.page;a=a.size;var d=a===void 0?"large":a;a=h(g!==void 0?g:g=b("CometPageVerificationBadge_page.graphql"),c);var e=a.verification_status;return e!=null&&e!=="NOT_VERIFIED"?b("React").jsx(b("CometLazyPopoverTrigger.react"),{popoverProps:{verificationBadge:e},popoverResource:i,position:"above",children:function(a,c){return b("React").jsx("span",{onMouseEnter:c,ref:a,children:b("React").jsx(b("CometPageVerificationIcon.react"),{size:d,verificationBadge:e})})}}):null}e.exports=a}),null);
__d("CometFeedPageVerifiedBadgeStrategy.react",["CometPageVerificationBadge.react","CometRelay","React","recoverableViolation","stylex","useCometFeedStoryMatchDebugger","CometFeedPageVerifiedBadgeStrategy_badge.graphql"],(function(a,b,c,d,e,f){"use strict";__p&&__p();var g;b("CometRelay").graphql;var h=b("CometRelay").useFragment;function a(a){__p&&__p();a=h(g!==void 0?g:g=b("CometFeedPageVerifiedBadgeStrategy_badge.graphql"),a.badge);b("useCometFeedStoryMatchDebugger")(a);a=a==null?void 0:(a=a.story)==null?void 0:a.actors;a=a||[];a=a[0];a=a===void 0?null:a;if(a===null){b("recoverableViolation")("Can't render a verified badge without at least one story actor","comet_feed");return null}return b("React").jsx("span",{className:"l9j0dhe7 qnrpqo6b",children:b("React").jsx(b("CometPageVerificationBadge.react"),{page:a,size:"small"})})}e.exports=a}),null);